#!/usr/bin/env bash
# Generate the scoped profiles (frontend, backend, infra) from the
# fullstack source of truth. Edit profiles/fullstack/ and re-run this.
#
#   ./build-profiles.sh
#
# Each generated profile is self-contained: its own .opencode/ (only the
# agents, commands, and skills it needs), opencode.json (only its MCPs),
# AGENTS.md, .env.example, and .ignore. Run a profile with:
#
#   cd profiles/<name> && opencode
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$ROOT/profiles/fullstack"
SRC_OC="$SRC/.opencode"

[ -d "$SRC_OC" ] || { echo "Missing source of truth: $SRC_OC"; exit 1; }
command -v node >/dev/null 2>&1 || { echo "node is required to generate profile configs"; exit 1; }

# Shared core — included in every profile.
CORE_AGENTS="architect.md tester.md review.md refactor.md commit.md docs.md"
CORE_COMMANDS="architect.md test.md review.md refactor.md commit.md docs.md"
CORE_SKILLS="testing"

# Filter the fullstack opencode.json down to a profile: keep only the named
# MCP servers (with the given enabled flags) and set/clear default_agent.
write_config() {
  local dest="$1" mcp_spec="$2" default_agent="$3"
  node -e '
    const fs = require("fs");
    const [src, mcpSpec, def] = process.argv.slice(1);
    const c = JSON.parse(fs.readFileSync(src));
    const want = {};
    mcpSpec.split(",").filter(Boolean).forEach(p => { const [k, v] = p.split("="); want[k] = v === "1"; });
    const all = c.mcp || {};
    const next = {};
    Object.keys(all).forEach(k => { if (k in want) { next[k] = all[k]; next[k].enabled = want[k]; } });
    c.mcp = next;
    if (def) c.default_agent = def; else delete c.default_agent;
    process.stdout.write(JSON.stringify(c, null, 4) + "\n");
  ' "$SRC/opencode.json" "$mcp_spec" "$default_agent" > "$dest/opencode.json"
}

build_profile() {
  local name="$1" default_agent="$2" mcp_spec="$3" agents="$4" cmds="$5" skills="$6"
  local dest="$ROOT/profiles/$name"

  rm -rf "$dest"
  mkdir -p "$dest/.opencode/agents" "$dest/.opencode/commands" "$dest/.opencode/skills"

  for a in $agents; do
    mkdir -p "$dest/.opencode/agents/$(dirname "$a")"
    cp "$SRC_OC/agents/$a" "$dest/.opencode/agents/$a"
  done
  for c in $cmds; do
    cp "$SRC_OC/commands/$c" "$dest/.opencode/commands/$c"
  done
  for s in $skills; do
    mkdir -p "$dest/.opencode/skills/$s"
    cp -R "$SRC_OC/skills/$s/." "$dest/.opencode/skills/$s/"
  done

  cp "$SRC/.env.example" "$dest/.env.example"
  cp "$SRC/.ignore" "$dest/.ignore"
  { printf '> **Profile: %s** — generated by build-profiles.sh. Edit profiles/fullstack/ and re-run to update.\n\n' "$name"
    cat "$SRC/AGENTS.md"; } > "$dest/AGENTS.md"

  write_config "$dest" "$mcp_spec" "$default_agent"

  echo "built $name: $(echo $agents | wc -w | tr -d ' ') agents, $(echo $cmds | wc -w | tr -d ' ') commands, $(echo $skills | wc -w | tr -d ' ') skills | mcp: $mcp_spec | default: ${default_agent:-<none>}"
}

build_profile "frontend" "frontend/frontend" "context7=1,playwright=1" \
  "frontend/frontend.md frontend/a11y-checker.md frontend/state-analyzer.md frontend/ui-analyzer.md frontend/performance-analyzer.md $CORE_AGENTS" \
  "frontend.md $CORE_COMMANDS" \
  "frontend $CORE_SKILLS"

build_profile "backend" "backend/backend" "context7=1,postgres=0" \
  "backend/backend.md backend/api-analyzer.md backend/auth-checker.md backend/db-analyzer.md backend/performance-analyzer.md security/security.md security/risk-scanner.md $CORE_AGENTS" \
  "backend.md security.md $CORE_COMMANDS" \
  "backend security $CORE_SKILLS"

build_profile "infra" "" "context7=1,github=0" \
  "infra/docker.md infra/compose.md infra/nginx.md infra/github-actions.md infra/deployment.md infra/docker-build-analyzer.md infra/compose-service-analyzer.md infra/nginx-routing-analyzer.md infra/github-actions-workflow-analyzer.md infra/deployment-readiness-checker.md security/security.md security/risk-scanner.md $CORE_AGENTS" \
  "docker.md compose.md nginx.md github-actions.md deploy.md deploy-check.md security.md $CORE_COMMANDS" \
  "infra/docker infra/compose infra/nginx infra/github-actions infra/deployment security $CORE_SKILLS"

# --- Framework profiles (narrower specializations) ---

build_profile "fastapi" "backend/backend" "context7=1,postgres=0" \
  "backend/backend.md backend/api-analyzer.md backend/auth-checker.md backend/db-analyzer.md backend/performance-analyzer.md security/security.md security/risk-scanner.md $CORE_AGENTS" \
  "backend.md security.md $CORE_COMMANDS" \
  "backend security frameworks/fastapi $CORE_SKILLS"

build_profile "nextjs" "frontend/frontend" "context7=1,playwright=1" \
  "frontend/frontend.md frontend/a11y-checker.md frontend/state-analyzer.md frontend/ui-analyzer.md frontend/performance-analyzer.md $CORE_AGENTS" \
  "frontend.md $CORE_COMMANDS" \
  "frontend frameworks/nextjs $CORE_SKILLS"

build_profile "python-sdk" "backend/backend" "context7=1" \
  "backend/backend.md security/security.md security/risk-scanner.md $CORE_AGENTS" \
  "backend.md security.md $CORE_COMMANDS" \
  "backend security frameworks/python-sdk $CORE_SKILLS"

build_profile "docs" "docs" "context7=1" \
  "docs.md architect.md review.md commit.md" \
  "docs.md architect.md review.md commit.md" \
  "frameworks/docs-mkdocs"

build_profile "docker" "" "context7=1" \
  "infra/docker.md infra/compose.md infra/docker-build-analyzer.md infra/compose-service-analyzer.md architect.md review.md commit.md" \
  "docker.md compose.md architect.md review.md commit.md" \
  "infra/docker infra/compose"

echo "Done. Profiles: fullstack (source) + frontend, backend, infra, fastapi, nextjs, python-sdk, docs, docker (generated)."
